version: '3'
services:
  sovryn-node:

    build:
        context: ./
        dockerfile: Dockerfile
        target: release

    entrypoint: ["npm", "run" , "start:test", "somesecretpassword"]
    
    volumes:
      - $HOME/Desktop/docker-data/sovryn-node:/var/www/html

    # npm run start

    dns:
      - 8.8.8.8
     

    environment:
     - FOO=aaaa


    restart: always
